# Site settings
title: 馨如姐姐杂货铺
email: zxr@xinru.me
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: 做好玩的让自己的开心的事情就好

# Social icons
facebook: xinnnru
linkedin: 张馨如
github: Litaya

footer: © Taken theme

# Build settings
markdown: kramdown
