# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Do what you like, and enjoy life
email: zxr@xinru.me
description: > # this means to ignore newlines until "baseurl:"
    我就是个享乐的主。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.xinru.me" # the base hostname & protocol for your site
twitter_username: xinru_zhang
github_username:  Litaya

# Build settings
markdown: kramdown
